version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: computersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/computersdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  db_data:
